### ISSUE TITLE
Video dont play sound & sometimes dont play

### ISSUE THREAD

**Issue by masterchop** [keijiro/VideoPlayerEffects#1]
Hello Keijiro,

Thanks for your awesome samples, this was the only desent solution i have found to play high quality videos in unity.
unfortunatelly the video sometimes dont play in the editor (not tested as standalone app yet) and when import then the audio is not there.
is there any limitation for the video?

Specs:
Unity **5.6.0f3**  ## **VR Project** 
Video info:
General
Complete name               : C:\Users\Extreme Tech\Downloads\VideoPlayerEffects-master\Assets\Test\Vicky\widevideo.mp4
Format                      : MPEG-4
Format profile              : Base Media / Version 2
Codec ID                    : mp42 (mp42/mp41)
File size                   : 422 MiB
Duration                    : 5 min
Overall bit rate mode       : Variable
Overall bit rate            : 10.5 Mb/s
Encoded date                : UTC 2017-03-31 12:00:26
Tagged date                 : UTC 2017-03-31 12:00:29
©TIM                        : 00:00:00:00
©TSC                        : 60
©TSZ                        : 1

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : Main@L5.2
Format settings, CABAC      : Yes
Format settings, ReFrames   : 3 frames
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 5 min
Bit rate                    : 10.2 Mb/s
Width                       : 4 096 pixels
Height                      : 1 536 pixels
Display aspect ratio        : 5.333
Frame rate mode             : Constant
Frame rate                  : 60.000 FPS
Standard                    : NTSC
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.027
Stream size                 : 409 MiB (97%)
Language                    : English
Encoded date                : UTC 2017-03-31 12:00:26
Tagged date                 : UTC 2017-03-31 12:00:26
Color range                 : Limited
Color primaries             : BT.709
Transfer characteristics    : BT.709
Matrix coefficients         : BT.709

Audio
ID                          : 2
Format                      : AAC
Format/Info                 : Advanced Audio Codec
Format profile              : LC
Codec ID                    : 40
Duration                    : 5 min
Source duration             : 5 min
Bit rate mode               : Variable
Bit rate                    : 317 kb/s
Maximum bit rate            : 425 kb/s
Channel(s)                  : 2 channels
Channel positions           : Front: L R
Sampling rate               : 48.0 kHz
Frame rate                  : 46.875 FPS (1024 spf)
Compression mode            : Lossy
Stream size                 : 12.7 MiB (3%)
Source stream size          : 12.7 MiB (3%)
Language                    : English
Encoded date                : UTC 2017-03-31 12:00:26
Tagged date                 : UTC 2017-03-31 12:00:26

for the audio i am using an audio source to play a mp3 file i extracted from the video but the audio imput in the video player plugin does not allow me to play the same mp3 is there any specific file format or any advantages to play the audio from the plugin against the audio source?

Thanks again for this plug in, this has been a limitation for me for a long time.

**Comment by keijiro** [comment]
Hi,

I think the issue you told is not relevant to this repository. If you have an issue with VideoPlayer itself, you should report it to Unity Technologies.

I'm closing this ticket. Please feel free to reopen it if this issue is actually relevant to this repository.

**Comment by masterchop** [comment]
just 1 quick question why if i created a new project the videos i imported are not even visible in the inspector but on your repo they just work right away. That is what made me think your repo was the video plug in itself.

**Comment by keijiro** [comment]
Actually I'm not sure why but I guess that the codec is wrong. VideoPlayer only supports H.264 for the MP4 container. The forum thread below would be helpful.

https://forum.unity3d.com/threads/correct-video-format-for-video-playback.446011/
