### ISSUE TITLE
skinner compatibility

### ISSUE THREAD

**Issue by nbac** [keijiro/VideoPlayerEffects#2]
could we use the skinner fx on videoplayer input?

**Comment by keijiro** [comment]
Skinner is a special effect for skinned mesh objects. I think it's not relevant to VideoPlayer.

I'm closing this ticket. Please feel free to reopen if you'd like to elaborate this topic.

**Comment by nbac** [comment]
i do understand. i´m not familiar with git issues it is less an issue than it is a wish.
i would like to have same systems/art (particles; fx etc) produced by the video input instead of a skinned mesh. since there is no tracking involved and the video does not produce any motion vectors it would be more random an just on point or on pixel emitter but  possible!?

**Comment by keijiro** [comment]
Possible.

The only question is who spends time/money for it.
